apiVersion: v2
name: bare-metal-fulfillment-operator-crds
description: CRDs for the Bare Metal Fulfillment Operator
type: application
version: 0.0.11-nightly.20260904.935fe0f.24.1
appVersion: 0.0.11-nightly.20260904.935fe0f.24.1
