apiVersion: v2
name: osac-operator
description: OSAC Operator - manages OSAC custom resources
type: application
version: 0.0.12-nightly.20260904.935fe0f.24.1
appVersion: 0.0.12-nightly.20260904.935fe0f.24.1
